//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Meta;
using UnityEngine;
using System.Collections;

public class VertexHandler : MetaBehaviour
{

    public Vector3 startPosition;
    Vector3 lastPosition;
    public Vector3 meshNodePostition;
    public int vertexId;
    public bool selected = false;
    bool firstTime = true;
    public Vector3[] previousVertices;

    public void setId(int i)
    {
        vertexId = i;
    }

    public void OnGrab()
    {
        Debug.Log("Grab");
        GameObject.Find("Cube").GetComponent<MainMesh>().PushUndo();
        startPosition = transform.position;
        lastPosition = transform.position;
    }

    public void OnHold()
    {
        Vector3 positionDelta = transform.position - lastPosition;
        GameObject.Find("Cube").GetComponent<MainMesh>().MovedControlPoint(vertexId, positionDelta, startPosition, transform.position);
        lastPosition = transform.position;
    }
    public void OnRelease()
    {
        Debug.Log("OnRelease");
        GameObject.Find("Cube").GetComponent<MainMesh>().snapControlPoints();
        
    }

    public void OnTouchEnter()
    {
        GetComponent<Renderer>().material.color = Color.yellow;
        //			Debug.Log("OnTouchEnter");
    }
    public void OnTouchHold()
    {
        //GetComponent<Renderer>().material.color = Color.green;
    }
    public void OnTouchDwell()
    {
        if (firstTime)
        {
            firstTime = false;
            selected = !selected;
            GameObject.Find("Cube").GetComponent<MainMesh>().handleSelect(vertexId, selected);
        }
    }
    public void OnTouchExit()
    {
        firstTime = true;
        GameObject.Find("Cube").GetComponent<MainMesh>().handleSelect(vertexId, selected);     
    }

    public void OnPinch()   
    {
        Debug.Log("OnPinch");
        GameObject.Find("Cube").GetComponent<MainMesh>().PushUndo();
        startPosition = transform.position;
        lastPosition = transform.position;
    }
    public void OnPinchHold()
    {
        Vector3 positionDelta = transform.position - lastPosition;
        GameObject.Find("Cube").GetComponent<MainMesh>().MovedControlPointExact(vertexId, positionDelta, transform.position);
        lastPosition = transform.position;
    }
    public void OnPinchRelease()
    {

    }

}

